name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}

    - name: Deploy to Production Server
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USER: ${{ secrets.REMOTE_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
          cd /home/debian/JPINVERSIONES
          git fetch origin master
          git reset --hard origin/master
          npm ci
          npm run build
          pm2 reload next-app || pm2 start npm --name "next-app" -- start
        EOF

    - name: Verify Deployment
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USER: ${{ secrets.REMOTE_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << EOF
          cd /home/debian/JPINVERSIONES
          if pm2 show next-app | grep -q "online"; then
            echo "Deployment successful: Application is running"
          else
            echo "Deployment failed: Application is not running"
            exit 1
          fi
        EOF
