name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navegar al directorio del proyecto
          cd /home/debian/JPINVERSIONES

          # Actualizar el repositorio
          git fetch origin master
          git reset --hard origin/master

          # Instalar dependencias
          npm ci

          # Construir el proyecto
          npm run build

          # Reiniciar la aplicación con PM2
          pm2 reload next-app || pm2 start npm --name "next-app" -- start

    - name: Verify Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/debian/JPINVERSIONES
          if pm2 show next-app | grep -q "online"; then
            echo "Deployment successful: Application is running"
          else
            echo "Deployment failed: Application is not running"
            exit 1
          fi
